HBM/md-components

- components/textfield/index.js
Support all input types which are convenient to enter with keyboard
> add email, search, tel and url to allowed types

- components/textfield/index.js
used for initial population: https://facebook.github.io/react/docs/forms.html#default-value
> add defaultValue prop

- components/chip/index.js
this was in before... what happened ?
> dont prevent default for enter

- components/list/List.scss
- components/list/index.js
- examples/js/components/listRoute.js
when rows specify onFocus and/or onBlur callbacks, the row is selectable and reacts to keyboard input (tab, up, down).
> List add focus keyboard

- components/textfield/index.js
> add autoComplete autoCorrect autoCapitalize and spellCheck

- components/textfield/index.js
- components/textfield/test/test.js
> textfield: add placeholder prop, fix defaultValue label

- components/chip/index.js
- components/chip/test/test.js
- examples/js/components/chipRoute.js
simplifies the focus handling. element is now a "stupid" component without state.
> Chip: refactor focus implementation

- components/chip/Chip.scss
- invert colors also on hover
- change cursor style (for the text)
- adjust gray of close button
> Chip: improve style according to spec

- components/list/List.scss
- components/list/index.js
- components/list/test/test.js
- examples/css/styles.scss
- examples/js/components/listRoute.js
- package.json
The prop "linkTo" uses the Link element from react-router to turn the entire row into a link.
The top level element then is a div instead of an ol to be valid HTML.
```jsx
<List>
<Row primary='Foo' icon={icon} linkTo='/foo' />
</List>
```
Also a style issue with three line rows has been fixed
> List: add link list

- package.json
the js file still has 2.5 MB. probably because of the icons 👎 
closes #99
> minify js and css

- components/slider/index.js
- components/slider/test/test.js
- examples/js/components/sliderRoute.js
- examples/js/script.js
also implemented steps. no animation yet.
> Slider: Fix implementation

- components/chip/Chip.scss
> vertically align input with chips

- components/navigation/index.js
> Navigation: fix overlay touch event propagation

- .codeclimate.yml
- .eslintrc
this repo needs still to be enabled at codeclimate
> add codeclimate config files

- components/navigation/Navigation.scss
> navigation: fix hiding scrollbar for few items

- components/button/Button.scss
> Button: sass improvements

- README.md
- css/base.scss
- css/colors.scss
> Color vars

- components/table/index.js
> use empty array as default value for table header

- examples/css/styles.scss
- examples/js/components/navigationRoute.js
- examples/js/script.js
> add navigation component to docs

- components/table/Table.scss
- components/table/index.js
- components/table/test/test.js
- examples/js/components/tableRoute.js
- index.js
This PR would fix the following issues:
- Handle click of row using Table Component #195 
- Table: Avoid Code Duplication #185
- Table: Uncaught error if cell is null #182
Let me know what you think.
/cc @armanneysi89 @armel22
> split table into multiple sub components

- src/js/textfield/index.scss
> textfield: make background transparent

- src/js/textfield/index.js
- src/js/textfield/test/test.js
> add htmlFor attribute to textfield and textarea

- src/css/base.scss
> fix body padding-top for mobile

- src/js/list/index.scss
> fix three-line spacing

- examples/src/bottomnavigationRoute.js
- examples/src/index.js
- examples/src/listRoute.js
- examples/src/navigationRoute.js
- examples/src/tabsRoute.js
- src/index.js
- src/js/bottomnavigation/index.js
- src/js/bottomnavigation/index.scss
- src/js/bottomnavigation/test/test.js
- src/js/button/index.scss
- src/js/list/index.js
- src/js/list/index.scss
- src/js/list/test/test.js
- src/js/navigation/index.js
- src/js/navigation/index.scss
- src/js/navigation/test/test.js
- src/js/shell/index.js
- src/js/tabs/index.js
- src/js/tabs/index.scss
- src/js/tabs/test/test.js
- webpack.config.js
> Router agnostic

- src/scss/navigation.scss
closes #326 
change focus color to "gray" to make focus movement visible
> remove nav focus outline/glow

- src/scss/checkbox.scss
> fix checkbox focus shadow

- src/scss/base.scss
please merge normalize before testing / reviewing this one to get the `margin: 0` for the `body`
> make base css simpler and use full width

- examples/src/selectRoute.js
- src/js/select/index.js
this is allows the label to be JSX. `currentTarget` is the dom node where the `onClick` function has been attached to.
> Select current target

- src/js/snackbar/index.js
https://reactjs.org/docs/typechecking-with-proptypes.html
> allow anything that can be rendered in snackbar

- src/scss/tabs.scss
our tabs are way to high after the `line-height` change
https://material.io/guidelines/components/tabs.html#tabs-specs
> fix tab height according to spec
