components/list/List.scss

Empty lists should occupy zero space (height). Thus the top/bottom padding should not be applied to the list but to the first/list rows of the list.

apply padding to last/first row instead of list

---

Makefile
components/modal/Modal.scss
components/modal/index.js
components/modal/test/test.js

- Remove scale effect (no such effect on android)
- Just use opacity
- Just CSS / no Motion & Spring lib dep
- Modal stays in the DOM even if not visible.
See also here:
https://www.youtube.com/watch?v=jbU5yRhSbKg
http://stackoverflow.com/questions/30507642/how-should-a-material-design-dialog-box-be-animated

Modal: improve animation

---

components/textfield/Textfield.scss

The spec implies font-size + 2px as line height. The line-height with the Roboto font used is font-size + 4px. Thus some css does not read as in spec.

Textfield: stick tighter to spec

---

examples/index.html

closes #109 
using my private gmail account. GA email invitations for fahri and mirco sent via email (gmail).
only tracking when hosted by hbm.github.io

add google analytics

---

components/select/Select.scss
components/select/index.js
components/select/test/test.js
examples/js/components/selectRoute.js

The implementation is correct. Unfortunately it doesn't work with the current version of React :)
https://github.com/facebook/react/issues/8308
It should be fixed with the next React version though.

select: add disabled property (fix #183)

---

components/navigation/Navigation.scss
components/navigation/index.js
components/navigation/test/test.js
examples/css/styles.scss
examples/js/components/navigationRoute.js

With this change the user is able to use as many levels as it wants.
The problem with the current implementation is we're losing the animation effect where sub menus grow and shrink. Having only one level makes it easy to animate because we can simply count the number of items in the sub menu, multiply this number with the height of each item and we have the height of each sub menu.
Having multiple levels makes this `height` animation much harder. We don't know the height of a sub menu inside a sub menu. Therefore we cannot set the height upfront. However I think this issue should not stop us from adding this change to the navigation component. If we really want the animation back where sub menus slide in and out we have to find a solution at some point in the future.
PR fix #205

navigation: allow nesting of multiple levels

---

src/components/textfield/index.js
src/components/textfield/test/test.js

Hello!
This proposed PR makes Textarea component work with [Inferno](https://github.com/trueadm/inferno) - React-like library with a focus on performance. For performance reasons there are on synthetic events in Inferno, so this PR moves `onChange` handler to use native `oninput`. 
Tests show no regression.

Make Textarea component compatible with Inferno

---

examples/src/selectRoute.js
examples/src/tableRoute.js
src/js/select/index.js
src/js/select/test/test.js
src/js/table/index.js
src/js/table/test/test.js

At the moment it is not possible to map an Array of values to be selected to an Array where a random index is `null` or `undefined`.
```js
const bitrates = [
9.6,
19.2,
93.75,
null,
'Auto'
]
```
With my PR it could work like this
```js
<Select
options=[
{value: 0, label: 9.6},
{value: 1, label: 19.2},
{value: 2, label: 93.75},
{value: 4, label: 'Auto'},
]
value={4}
/>
```
Syntax (`options` and `value`) is take from [react-select](https://github.com/JedWatson/react-select).

stop using index for setting selected value

---

src/js/snackbar/index.scss

makes the full width container (invisible) pass through pointer events.
closes #270

fix pointer events

---

src/js/checkbox/index.scss

closes #207 
reduces clickable / touchable size on the left. i think this is ok.
alternative would be to shift (negative margin, transform) the checkbox keeping the touchable area on the left.

fix checkbox alignment

---

src/js/list/index.scss

closes #242 
I don't really see an advantage, but as `*` is considered bad practice... 😸

list: remove wildcard selector where possible

---

src/js/navigation/index.js

Navigation: stop event propagation to underlying elements

---

examples/src/tableRoute.js
src/css/base.scss
src/js/select/index.js
src/js/select/index.scss
src/js/select/test/test.js
src/js/table/test/test.js

closes #311 and #310 
the font-size was overruled by user agent `<button>` rule.

Fix select

---

src/scss/checkbox.scss

the underlying input was not positioned explicitly.
in firefox the input was __outside__ the enclosing div (causing tests to fail).

position underlying input inside of enclosing div

---

src/scss/base.scss

before 
after
Have a look at the lower part of the <kbd>g</kbd>.
It also fixes the box when highlighting DOM nodes within the inspector. It is the same value bootstrap uses https://github.com/twbs/bootstrap/blob/502ac7ee4d13669e644b9181f1e014ce0ea1f089/dist/css/bootstrap.css#L93.

fix line height and use unitless value

---

src/js/header/index.js
src/scss/header.scss

before
after
was a bit tricky because of flex and `text-overflow: ellipsis`. https://css-tricks.com/flexbox-truncated-text/

fix subtitle wrap and overflow

---

src/scss/textfield.scss

Currently our `readOnly` textfield looks like a normal textfield. This can be very confusing for the user. I've used the `disabled` spec and applied it to our `readOnly` textfields.
https://material.io/guidelines/components/text-fields.html#text-fields-states

improve style for read only textfield

---

src/js/chip/index.js
src/scss/chip.scss

The old style would also apply to custom SVGs inside our Chips. That's not what we want.
In our application we'd get incorrect styles when an LED (svg icon from material design) is inside the Chip component.

make chip css selectors more precise

---

src/js/modal/index.js
src/js/modal/test/test.js

fixes:
- click could trigger underlying elements
- disable scroll (by touch, mouse or keys) when modal is visible
add:
- close with ESC key
- blur the active element when openening the modal
tested on iOS

Modal fix: disable scroll when modal is open, prevent click-through

---

src/js/header/index.js

immediately shows shadow when scrolling on mobile. Previous impl added shadow after touchend.
https://stackoverflow.com/questions/2863547/javascript-scroll-event-for-iphone-ipad
tested on iOS

Header fix: attach to touchmove event to trigger this.onScroll
